// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: message.proto

package biddingsys_message_pb

import (
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From     string            `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`         //wyong, 20200826
	Wantlist *Message_Wantlist `protobuf:"bytes,2,opt,name=wantlist,proto3" json:"wantlist,omitempty"` //repeated bytes blocks = 2;		// used to send Blocks in bitswap 1.0.0
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetWantlist() *Message_Wantlist {
	if x != nil {
		return x.Wantlist
	}
	return nil
}

type Message_Wantlist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*Message_Wantlist_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // a list of wantlist entries
	Full    bool                      `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`      // whether this is the full wantlist. default to false
}

func (x *Message_Wantlist) Reset() {
	*x = Message_Wantlist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_Wantlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Wantlist) ProtoMessage() {}

func (x *Message_Wantlist) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Wantlist.ProtoReflect.Descriptor instead.
func (*Message_Wantlist) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Wantlist) GetEntries() []*Message_Wantlist_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Message_Wantlist) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

type Message_Wantlist_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string                        `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`            // the block cid (cidV0 in bitswap 1.0.0, cidV1 in bitswap 1.1.0)
	Priority int32                         `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"` // the priority (normalized). default to 1
	Cancel   bool                          `protobuf:"varint,3,opt,name=cancel,proto3" json:"cancel,omitempty"`     // whether this revokes an entry
	Bids     []*Message_Wantlist_Entry_Bid `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`          //wyong, 20190115
}

func (x *Message_Wantlist_Entry) Reset() {
	*x = Message_Wantlist_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_Wantlist_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Wantlist_Entry) ProtoMessage() {}

func (x *Message_Wantlist_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Wantlist_Entry.ProtoReflect.Descriptor instead.
func (*Message_Wantlist_Entry) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Message_Wantlist_Entry) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Message_Wantlist_Entry) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message_Wantlist_Entry) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

func (x *Message_Wantlist_Entry) GetBids() []*Message_Wantlist_Entry_Bid {
	if x != nil {
		return x.Bids
	}
	return nil
}

type Message_Wantlist_Entry_Bid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid  []byte `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`   //wyong, 20190115
	From []byte `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"` //wyong, 20190118
}

func (x *Message_Wantlist_Entry_Bid) Reset() {
	*x = Message_Wantlist_Entry_Bid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_Wantlist_Entry_Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Wantlist_Entry_Bid) ProtoMessage() {}

func (x *Message_Wantlist_Entry_Bid) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Wantlist_Entry_Bid.ProtoReflect.Descriptor instead.
func (*Message_Wantlist_Entry_Bid) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *Message_Wantlist_Entry_Bid) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *Message_Wantlist_Entry_Bid) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x15, 0x62, 0x69, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x79, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x62, 0x1a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x03, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x49, 0x0a, 0x08, 0x77, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x62, 0x69, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x73, 0x79, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73, 0x74,
	0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x08, 0x77, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73, 0x74,
	0x1a, 0xb7, 0x02, 0x0a, 0x08, 0x57, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x4d, 0x0a,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x62, 0x69, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x79, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x57,
	0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x04, 0xc8,
	0xde, 0x1f, 0x00, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x75, 0x6c, 0x6c,
	0x1a, 0xc7, 0x01, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x12, 0x4b, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31,
	0x2e, 0x62, 0x69, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x79, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x57,
	0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x42, 0x69,
	0x64, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x01, 0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x1a, 0x2b, 0x0a,
	0x03, 0x42, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_proto_goTypes = []interface{}{
	(*Message)(nil),                    // 0: biddingsys.message.pb.Message
	(*Message_Wantlist)(nil),           // 1: biddingsys.message.pb.Message.Wantlist
	(*Message_Wantlist_Entry)(nil),     // 2: biddingsys.message.pb.Message.Wantlist.Entry
	(*Message_Wantlist_Entry_Bid)(nil), // 3: biddingsys.message.pb.Message.Wantlist.Entry.Bid
}
var file_message_proto_depIdxs = []int32{
	1, // 0: biddingsys.message.pb.Message.wantlist:type_name -> biddingsys.message.pb.Message.Wantlist
	2, // 1: biddingsys.message.pb.Message.Wantlist.entries:type_name -> biddingsys.message.pb.Message.Wantlist.Entry
	3, // 2: biddingsys.message.pb.Message.Wantlist.Entry.bids:type_name -> biddingsys.message.pb.Message.Wantlist.Entry.Bid
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_Wantlist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_Wantlist_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_Wantlist_Entry_Bid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
