package types

// Code generated by github.com/CovenantSQL/HashStablePack DO NOT EDIT.

import (
	"fmt"

	hsp "github.com/CovenantSQL/HashStablePack/marshalhash"

        //wyong, 20200827 
        "github.com/siegfried415/gdf-rebuild/utils/callinfo"
)

// MarshalHash marshals for hash
func (z *UrlBidding) MarshalHash() (o []byte, err error) {
	//fmt.Printf("UrlBidding/MarshalHash(10), stack=%s\n", callinfo.Stacks())

	var b []byte
	o = hsp.Require(b, z.Msgsize())

	/* todo, wyong, 20200802 
	// map header, size 2
	o = append(o, 0x82)
	o = hsp.AppendArrayHeader(o, uint32(len(z.Args)))
	for za0001 := range z.Args {
		// map header, size 2
		o = append(o, 0x82)
		o = hsp.AppendString(o, z.Args[za0001].Name)
		o, err = hsp.AppendIntf(o, z.Args[za0001].Value)
		if err != nil {
			return
		}
	}
	*/

	o = hsp.AppendString(o, z.Url)

	//wyong, 20200817 
	o = hsp.AppendFloat64(o, z.Probability) 

	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *UrlBidding) Msgsize() (s int) {
	/* todo, wyong, 20200802 
	s = 1 + 5 + hsp.ArrayHeaderSize
	for za0001 := range z.Args {
		s += 1 + 5 + hsp.StringPrefixSize + len(z.Args[za0001].Name) + 6 + hsp.GuessSize(z.Args[za0001].Value)
	}
	*/

	s += 8 + hsp.StringPrefixSize + len(z.Url) + hsp.Float64Size
	return
}

/* wyong, 20200802 
// MarshalHash marshals for hash
func (z *QueryKey) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 3
	o = append(o, 0x83)
	o = hsp.AppendUint64(o, z.ConnectionID)
	if oTemp, err := z.NodeID.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	o = hsp.AppendUint64(o, z.SeqNo)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *QueryKey) Msgsize() (s int) {
	s = 1 + 13 + hsp.Uint64Size + 7 + z.NodeID.Msgsize() + 6 + hsp.Uint64Size
	return
}

// MarshalHash marshals for hash
func (z QueryType) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	o = hsp.AppendInt32(o, int32(z))
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z QueryType) Msgsize() (s int) {
	s = hsp.Int32Size
	return
}
*/


// MarshalHash marshals for hash
func (z *UrlBiddingMessage) MarshalHash() (o []byte, err error) {
	fmt.Printf("UrlBiddingMessage/MarshalHash(10), stack=%s\n", callinfo.Stacks())

	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 3
	o = append(o, 0x83)
	if oTemp, err := z.Envelope.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	// map header, size 2
	o = append(o, 0x82)
	if oTemp, err := z.Header.UrlBiddingHeader.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	if oTemp, err := z.Header.DefaultHashSignVerifierImpl.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	// map header, size 1
	o = append(o, 0x81)
	o = hsp.AppendArrayHeader(o, uint32(len(z.Payload.Requests)))
	for za0001 := range z.Payload.Requests {
		if oTemp, err := z.Payload.Requests[za0001].MarshalHash(); err != nil {
			return nil, err
		} else {
			o = hsp.AppendBytes(o, oTemp)
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *UrlBiddingMessage) Msgsize() (s int) {
	s = 1 + 9 + z.Envelope.Msgsize() + 7 + 1 + 14 + z.Header.UrlBiddingHeader.Msgsize() + 28 + z.Header.DefaultHashSignVerifierImpl.Msgsize() + 8 + 1 + 8 + hsp.ArrayHeaderSize
	for za0001 := range z.Payload.Requests{
		s += z.Payload.Requests[za0001].Msgsize()
	}
	return
}

// MarshalHash marshals for hash
func (z *UrlBiddingHeader) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 8
	o = append(o, 0x88)
	o = hsp.AppendUint64(o, z.BatchCount)
	o = hsp.AppendUint64(o, z.ConnectionID)
	if oTemp, err := z.DomainID.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	if oTemp, err := z.NodeID.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	if oTemp, err := z.QueriesHash.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	o = hsp.AppendInt32(o, int32(z.QueryType))
	o = hsp.AppendUint64(o, z.SeqNo)
	o = hsp.AppendTime(o, z.Timestamp)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *UrlBiddingHeader) Msgsize() (s int) {
	s = 1 + 11 + hsp.Uint64Size + 13 + hsp.Uint64Size + 11 + z.DomainID.Msgsize() + 7 + z.NodeID.Msgsize() + 12 + z.QueriesHash.Msgsize() + 10 + hsp.Int32Size + 6 + hsp.Uint64Size + 10 + hsp.TimeSize
	return
}

// MarshalHash marshals for hash
func (z *UrlBiddingPayload) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 1
	o = append(o, 0x81)
	o = hsp.AppendArrayHeader(o, uint32(len(z.Requests)))
	for za0001 := range z.Requests{
		if oTemp, err := z.Requests[za0001].MarshalHash(); err != nil {
			return nil, err
		} else {
			o = hsp.AppendBytes(o, oTemp)
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *UrlBiddingPayload) Msgsize() (s int) {
	s = 1 + 8 + hsp.ArrayHeaderSize
	for za0001 := range z.Requests {
		s += z.Requests[za0001].Msgsize()
	}
	return
}

// MarshalHash marshals for hash
func (z *SignedUrlBiddingHeader) MarshalHash() (o []byte, err error) {
	var b []byte
	o = hsp.Require(b, z.Msgsize())
	// map header, size 2
	o = append(o, 0x82)
	if oTemp, err := z.DefaultHashSignVerifierImpl.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	if oTemp, err := z.UrlBiddingHeader.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = hsp.AppendBytes(o, oTemp)
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SignedUrlBiddingHeader) Msgsize() (s int) {
	s = 1 + 28 + z.DefaultHashSignVerifierImpl.Msgsize() + 14 + z.UrlBiddingHeader.Msgsize()
	return
}
